jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 8081:8081
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        working-directory: tests/mytest
        env:
          SELENIUM_HOST: localhost
          SELENIUM_PORT: 8081
        run: gradle test
