name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for Selenium to start
        run: |
          echo "Waiting for Selenium to be ready..."
          for i in {1..30}; do
            curl -s http://selenium:4444/status && break
            sleep 1
          done

      - name: Run tests
        working-directory: tests/mytest
        env:
          SELENIUM_HOST: selenium
          SELENIUM_PORT: 4444
        run: gradle test
